### ISSUE TITLE
TypeScript type questions

### ISSUE THREAD

**Issue by ottob** [chartiful/react-charts#2]
Hi and thanks for a nice library. I tried to copy the code from the LineGraph [readme](https://www.npmjs.com/package/@chartiful/react-line-graph#example) but ran into a couple issues:

1. `data`, `width` and `height` has to be set on both BaseChartConfig and LineGraphConfig https://github.com/chartiful/react-charts/blob/4643342d0e4388cfabd12c296bb6c28e90adc85c/types.ts#L2 Shouldn't it be enough to set these in one these place?
2. I had to set these on LineGraphConfig `hasLine={true}`, `hasShadow={false}`, `dotSize={5}`. Shouldn't they perhaps be optional and have sensible defaults? Or the readme code updated so copy pasting works 😀

**Comment by seanwatters** [comment]
Hey, thank you for reaching out! 

We totally do need to update the README and fix the issue with types in TypeScript. A lot of this code is being reused from the React Native project and needs to be cleaned up / web-ified (the typing issue is also present on the RN project though too). 

I've been a little bit busy with some other things lately and haven't had time to make these fixes, but will try to get to them this weekend. Thanks so much for bringing them up though.

**Comment by seanwatters** [comment]
The TypeScript issue should be resolved now if you upgrade to the latest versions.

I'm looking into the issue with the defaults on LineGraphConfig.

**Comment by seanwatters** [comment]
@ottob Both issues should be resolved now if you upgrade to `@chartiful/react-line-graph v0.1.5` and `@chartiful/react-chart-builder v0.1.6`.

Let me know if you see anything else that comes up!

**Comment by ottob** [comment]
Hi, thanks for the quick fixes. Ive found a couple more issues:
1. there is still a small issue in the readme example for LineGraph:
https://github.com/chartiful/react-charts/blob/trunk/README.md#example
```js
    xAxisLabelStyle: {
      prefix: '$',
      offset: 0
    }
```
should be:
```js
    xAxisLabelStyle: {
      prefix: '$',
      xOffset: 0
    }
```
2. shouldn't `interface LineGraphConfig` have `labels?: string[]` here https://github.com/chartiful/react-charts/blob/50e20ebdaf1caa7b5c2a2dec18072adab820fffb/types.ts#L76
3. the readme example for LineGraph has `width` defined two times. In my case the graph looked better without `width` specified in the style prop.
4. Im trying to plot body weight over time (in kg) using this code:
```ts
<LineGraph
              data={[85, 82, 79, 75, 76]}
              width={500}
              height={300}
              lineColor="#347975"
              dotColor="#347975"
              lineWidth={3}
              isBezier
              hasDots={true}
              baseConfig={{
                startAtZero: false,
                hasXAxisBackgroundLines: true,
                hasYAxisBackgroundLines: true,
                xAxisLabelCount: 5,
                xAxisLabelStyle: {
                  xOffset: 0,
                },
              }}
              style={{
                marginBottom: 30,
                padding: 10,
                paddingTop: 20,
                borderRadius: 20,
                backgroundColor: `#dbf0ef`,
              }}
            />
```
I got a graph like this: 
<img width="535" alt="Screenshot 2020-08-13 at 10 55 16" src="https://user-images.githubusercontent.com/67104/90114792-857ff100-dd53-11ea-8d63-e9c09e15a771.png">
I think it would be easier to read the graph if:
1. xAxisLabels matched the data points? In this case [85, 82, 79, 75, 76]. Or can I set them manually?
1. labels (x and y) aligned horizontally and vertically with the BackgroundLines
1. labels (x and y) aligned horizontally and vertically with the dots
1. yAxisBackgroundLines where visible if set to true.

What do you think?

In my use case it would also be nice if the bar x axis could be squeezed somehow to make a "flatter" graph. Since the weight changes in this case is not as large as it looks. Is there a way to do this?
